torchrun --nproc_per_node=4 --master_port=20001 fastchat/train/train.py \
    --model_name_or_path facebook/opt-350m \
    --data_path ~/datasets/hardcoded.json \
    --bf16 False \
    --fp16 True \
    --output_dir output \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1200 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --gradient_checkpointing True \
    --lazy_preprocess False
