torchrun --nproc_per_node=16 --master_port=20001 fastchat/train/train.py \
    --model_name_or_path /nfs/projects/mbzuai/ext_hao.zhang/hao/dataset/llama-7b \
    --data_path /nfs/projects/mbzuai/ext_hao.zhang/hao/dataset/sharegpt_20230422_clean_lang_identity.json \
    --fp16 \
    --output_dir output_7b \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "steps" \
    --eval_steps 1500 \
    --save_strategy "steps" \
    --save_steps 1500 \
    --save_total_limit 8 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.04 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True

