torchrun --nproc_per_node=8 --master_port=11000 chatserver/train/alpaca_train.py \
    --model_name_or_path /home/ubuntu/llama_weights/hf-llama-7b \
    --data_path /home/ubuntu/datasets/alpaca_data.json \
    --fp16 True \
    --output_dir . \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
